module.exports = {
    docs: [
        'quick-start/quick-start',
        {
            type: 'category',
            label: 'Introduction',
            collapsed: true,
            link: {
                type: 'doc',
                id: 'introduction/introduction',
            },
            items: [
                'introduction/setting-up',
                'introduction/first-crawler',
                'introduction/adding-more-urls',
                'introduction/real-world-project',
                'introduction/crawling',
                'introduction/scraping',
                'introduction/saving-data',
                'introduction/refactoring',
                'introduction/deployment',
            ],
        },
        {
            type: 'category',
            label: 'Concepts',
            collapsed: true,
            link: {
                type: 'generated-index',
                title: 'Concepts',
                description:
                    'Learn how the core components of Crawlee work - crawlers, request routing, storages, sessions, and more.',
                slug: '/concepts',
                keywords: ['concepts'],
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: '03_concepts',
                },
            ],
        },
        {
            type: 'category',
            label: 'Guides',
            collapsed: true,
            link: {
                type: 'generated-index',
                title: 'Guides',
                description:
                    'Task-oriented guides for common crawling and scraping scenarios, integrations, and migrations.',
                slug: '/guides',
                keywords: ['guides'],
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: '04_guides',
                },
            ],
        },
        {
            type: 'category',
            label: 'Deployment',
            collapsed: true,
            link: {
                type: 'generated-index',
                title: 'Deployment guides',
                description: 'Here you can find guides on how to deploy your crawlers to various cloud providers.',
                slug: '/deployment',
            },
            items: [
                {
                    type: 'doc',
                    id: 'deployment/apify-platform',
                    label: 'Deploy on Apify',
                },
                {
                    type: 'doc',
                    id: 'deployment/aws-lambda',
                    label: 'Deploy on AWS Lambda',
                },
                {
                    type: 'category',
                    label: 'Deploy to Google Cloud',
                    items: ['deployment/gcp-cloud-run-functions', 'deployment/gcp-cloud-run'],
                },
            ],
        },
        {
            type: 'category',
            label: 'Upgrading',
            collapsed: true,
            link: {
                type: 'generated-index',
                title: 'Upgrading',
                slug: '/upgrading',
                keywords: ['upgrading'],
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: '06_upgrading',
                },
            ],
        },
        {
            type: 'doc',
            label: 'Changelog',
            id: 'changelog',
        },
    ],
};
