name: CI (master)

on:
  push:
    branches:
      - master
    tags-ignore:
      - "**" # Ignore all tags to avoid duplicate executions triggered by tag pushes.

concurrency:
  group: release
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  doc_checks:
    name: Doc checks
    uses: ./.github/workflows/_check_docs.yaml

  doc_release:
    # Skip this for non-"docs" commits.
    if: startsWith(github.event.head_commit.message, 'docs')
    name: Doc release
    needs: [doc_checks]
    permissions:
      contents: write
      pages: write
      id-token: write
    uses: ./.github/workflows/manual_release_docs.yaml
    with:
      # Use the same ref as the one that triggered the workflow.
      ref: ${{ github.ref }}
    secrets: inherit

  code_checks:
    name: Code checks
    uses: ./.github/workflows/_check_code.yaml

  tests:
    # Skip this for "docs" commits.
    if: "!startsWith(github.event.head_commit.message, 'docs')"
    name: Tests
    uses: ./.github/workflows/_tests.yaml
    secrets: inherit

  beta_release:
    # Run this only for "feat", "fix", "perf", "refactor" and "style" commits.
    if: >-
      startsWith(github.event.head_commit.message, 'feat') ||
      startsWith(github.event.head_commit.message, 'fix') ||
      startsWith(github.event.head_commit.message, 'perf') ||
      startsWith(github.event.head_commit.message, 'refactor') ||
      startsWith(github.event.head_commit.message, 'style')
    name: Beta release
    needs: [code_checks, tests]
    permissions:
      contents: write
      id-token: write
      pages: write
    uses: ./.github/workflows/manual_release_beta.yaml
    secrets: inherit
