name: CI (PR)

on:
  # Runs whenever a pull request is opened or updated.
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  pr_title_check:
    name: PR title check
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  checks:
    name: Checks
    uses: ./.github/workflows/_checks.yaml
    secrets: inherit
