name: Code quality checks

on:
  pull_request_target:

jobs:
  check_version_availability:
    name: Check version availability
    uses: ./.github/workflows/check_version_availability.yaml

  lint_and_type_checks:
    name: Run lint and type checks
    uses: ./.github/workflows/lint_and_type_checks.yaml

  unit_tests:
    name: Run unit tests
    needs: [lint_and_type_checks]
    uses: ./.github/workflows/unit_tests.yaml
